// ═══════════════════════════════════════════════════════════
//  GAME LEVELS DEFINITIONS
//  12-15 levels per game, transitioning from easy to medium to hard.
// ═══════════════════════════════════════════════════════════

export const GAME_LEVELS = {
  "math/addition": [
    { id: 1, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 2, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 3, difficulty: "easy", questionCount: 6, passThreshold: 60 },
    { id: 4, difficulty: "easy", questionCount: 6, passThreshold: 70 },
    { id: 5, difficulty: "easy", questionCount: 8, passThreshold: 70 },
    { id: 6, difficulty: "medium", questionCount: 8, passThreshold: 70 },
    { id: 7, difficulty: "medium", questionCount: 8, passThreshold: 75 },
    { id: 8, difficulty: "medium", questionCount: 10, passThreshold: 75 },
    { id: 9, difficulty: "medium", questionCount: 10, passThreshold: 80 },
    { id: 10, difficulty: "medium", questionCount: 10, passThreshold: 80 },
    { id: 11, difficulty: "hard", questionCount: 10, passThreshold: 80 },
    { id: 12, difficulty: "hard", questionCount: 10, passThreshold: 85 },
    { id: 13, difficulty: "hard", questionCount: 12, passThreshold: 85 },
    { id: 14, difficulty: "hard", questionCount: 12, passThreshold: 90 },
    { id: 15, difficulty: "hard", questionCount: 15, passThreshold: 100 },
  ],
  "math/subtraction": [
    { id: 1, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 2, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 3, difficulty: "easy", questionCount: 6, passThreshold: 60 },
    { id: 4, difficulty: "easy", questionCount: 6, passThreshold: 70 },
    { id: 5, difficulty: "easy", questionCount: 8, passThreshold: 70 },
    { id: 6, difficulty: "medium", questionCount: 8, passThreshold: 70 },
    { id: 7, difficulty: "medium", questionCount: 8, passThreshold: 75 },
    { id: 8, difficulty: "medium", questionCount: 10, passThreshold: 75 },
    { id: 9, difficulty: "medium", questionCount: 10, passThreshold: 80 },
    { id: 10, difficulty: "medium", questionCount: 10, passThreshold: 80 },
    { id: 11, difficulty: "hard", questionCount: 10, passThreshold: 80 },
    { id: 12, difficulty: "hard", questionCount: 10, passThreshold: 85 },
    { id: 13, difficulty: "hard", questionCount: 12, passThreshold: 85 },
    { id: 14, difficulty: "hard", questionCount: 12, passThreshold: 90 },
    { id: 15, difficulty: "hard", questionCount: 15, passThreshold: 100 },
  ],
  "math/multiply": [
    { id: 1, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 2, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 3, difficulty: "easy", questionCount: 6, passThreshold: 60 },
    { id: 4, difficulty: "easy", questionCount: 6, passThreshold: 70 },
    { id: 5, difficulty: "easy", questionCount: 8, passThreshold: 70 },
    { id: 6, difficulty: "medium", questionCount: 8, passThreshold: 70 },
    { id: 7, difficulty: "medium", questionCount: 8, passThreshold: 75 },
    { id: 8, difficulty: "medium", questionCount: 10, passThreshold: 75 },
    { id: 9, difficulty: "medium", questionCount: 10, passThreshold: 80 },
    { id: 10, difficulty: "medium", questionCount: 10, passThreshold: 80 },
    { id: 11, difficulty: "hard", questionCount: 10, passThreshold: 80 },
    { id: 12, difficulty: "hard", questionCount: 10, passThreshold: 85 },
    { id: 13, difficulty: "hard", questionCount: 12, passThreshold: 85 },
    { id: 14, difficulty: "hard", questionCount: 12, passThreshold: 90 },
    { id: 15, difficulty: "hard", questionCount: 15, passThreshold: 100 },
  ],
  "math/division": [
    { id: 1, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 2, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 3, difficulty: "easy", questionCount: 6, passThreshold: 60 },
    { id: 4, difficulty: "easy", questionCount: 6, passThreshold: 70 },
    { id: 5, difficulty: "easy", questionCount: 8, passThreshold: 70 },
    { id: 6, difficulty: "medium", questionCount: 8, passThreshold: 70 },
    { id: 7, difficulty: "medium", questionCount: 8, passThreshold: 75 },
    { id: 8, difficulty: "medium", questionCount: 10, passThreshold: 75 },
    { id: 9, difficulty: "medium", questionCount: 10, passThreshold: 80 },
    { id: 10, difficulty: "medium", questionCount: 10, passThreshold: 80 },
    { id: 11, difficulty: "hard", questionCount: 10, passThreshold: 80 },
    { id: 12, difficulty: "hard", questionCount: 10, passThreshold: 85 },
    { id: 13, difficulty: "hard", questionCount: 12, passThreshold: 85 },
    { id: 14, difficulty: "hard", questionCount: 12, passThreshold: 90 },
    { id: 15, difficulty: "hard", questionCount: 15, passThreshold: 100 },
  ],
  "finance/price-compare": [
    { id: 1, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 2, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 3, difficulty: "easy", questionCount: 6, passThreshold: 60 },
    { id: 4, difficulty: "easy", questionCount: 6, passThreshold: 70 },
    { id: 5, difficulty: "medium", questionCount: 8, passThreshold: 70 },
    { id: 6, difficulty: "medium", questionCount: 8, passThreshold: 75 },
    { id: 7, difficulty: "medium", questionCount: 10, passThreshold: 75 },
    { id: 8, difficulty: "hard", questionCount: 10, passThreshold: 80 },
    { id: 9, difficulty: "hard", questionCount: 10, passThreshold: 85 },
    { id: 10, difficulty: "hard", questionCount: 12, passThreshold: 90 },
  ],
  "finance/discount": [
    { id: 1, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 2, difficulty: "easy", questionCount: 5, passThreshold: 60 },
    { id: 3, difficulty: "medium", questionCount: 6, passThreshold: 60 },
    { id: 4, difficulty: "medium", questionCount: 6, passThreshold: 70 },
    { id: 5, difficulty: "medium", questionCount: 8, passThreshold: 70 },
    { id: 6, difficulty: "medium", questionCount: 8, passThreshold: 75 },
    { id: 7, difficulty: "hard", questionCount: 10, passThreshold: 75 },
    { id: 8, difficulty: "hard", questionCount: 10, passThreshold: 80 },
    { id: 9, difficulty: "hard", questionCount: 12, passThreshold: 85 },
    { id: 10, difficulty: "hard", questionCount: 12, passThreshold: 90 },
  ]
};
