// ═══════════════════════════════════════════════════════════
//  CONSTANTS — barcha konstantalar shu yerda
// ═══════════════════════════════════════════════════════════

import { PALETTE, PREMIUM, CHART, GARDEN } from "./tokens.js";

// Theme obyekti endi tokens.js'dan quriladi.
// Bazaviy kalitlar (bg, sur, ac, ...) qiymatlari o'zgarmagan — vizual 0 farq.
// Yangi additiv kalitlar: gold, goldGrad, chart, garden.
export const MK = d => ({
  ...(d ? PALETTE.dark : PALETTE.light),
  gold: PREMIUM.gold,
  goldGrad: PREMIUM.grad,
  chart: CHART,
  garden: GARDEN,
});

export const KATS = [
  {id:"oziq",     c:"#10b981"},
  {id:"transport",c:"#3b82f6"},
  {id:"kiyim",    c:"#8b5cf6"},
  {id:"sog",      c:"#ef4444"},
  {id:"kommunal", c:"#f59e0b"},
  {id:"konil",    c:"#ec4899"},
  {id:"talim",    c:"#06b6d4"},
  {id:"hadya",    c:"#f43f5e"},
  {id:"boshqa",   c:"#94A3B8"},
];

export const KN = {
  uz: ["Oziq-ovqat","Transport","Kiyim","Sog'liq","Kommunal","Ko'ngil ochar","Ta'lim","Hadya","Boshqa"],
  ru: ["Продукты","Транспорт","Одежда","Здоровье","Коммунальные","Развлечения","Образование","Подарок","Другое"],
  en: ["Food","Transport","Clothing","Health","Utilities","Entertainment","Education","Gift","Other"],
  kk: ["Азық-түлік","Көлік","Киім","Денсаулық","Коммуналдық","Ойын-сауық","Білім","Сыйлық","Басқа"],
  ky: ["Азық-түлүк","Транспорт","Кийим","Ден соолук","Коммуналдык","Көңүл ачуу","Билим","Белек","Башка"],
  tg: ["Хӯрокворӣ","Нақлиёт","Либос","Тандурустӣ","Коммуналӣ","Дилхушӣ","Таҳсилот","Туҳфа","Дигар"],
  qr: ["Aziq-awqat","Transport","Kiyim","Densawliq","Kommunal","Kewil-ashar","Bilim","Sawg'a","Basqa"],
};

export const DARS = [
  {id:"oylik",    c:"#10b981"},
  {id:"qoshimcha",c:"#f59e0b"},
  {id:"biznes",   c:"#3b82f6"},
  {id:"sovga",    c:"#8b5cf6"},
  {id:"boshqa",   c:"#94A3B8"},
];

export const DN = {
  uz: ["Oylik maosh","Qo'shimcha","Biznes","Sovg'a","Boshqa"],
  ru: ["Зарплата","Доп.доход","Бизнес","Подарок","Другое"],
  en: ["Salary","Additional","Business","Gift","Other"],
  kk: ["Жалақы","Қосымша табыс","Бизнес","Сыйлық","Басқа"],
  ky: ["Айлык акы","Кошумча киреше","Бизнес","Белек","Башка"],
  tg: ["Маош","Даромади иловагӣ","Бизнес","Туҳфа","Дигар"],
  qr: ["Ayliq miynet","Qosimsha tabil","Biznes","Sawg'a","Basqa"],
};

export const VALS = [
  {id:"uzs",b:"so'm",k:1},
  {id:"usd",b:"$",k:12800},
  {id:"rub",b:"₽",k:140},
  {id:"eur",b:"€",k:13900},
  {id:"kzt",b:"₸",k:26},
  {id:"kgs",b:"сом",k:145},
  {id:"tjs",b:"сомони",k:1180},
  {id:"try",b:"₺",k:380},
  {id:"gbp",b:"£",k:16200},
  {id:"aed",b:"د.إ",k:3485},
];

export const COUNTRIES = [
  {code:"uz",dial:"+998",flag:"🇺🇿",uz:"O'zbekiston",ru:"Узбекистан",en:"Uzbekistan",val:"uzs"},
  {code:"ru",dial:"+7",flag:"🇷🇺",uz:"Rossiya",ru:"Россия",en:"Russia",val:"rub"},
  {code:"kz",dial:"+7",flag:"🇰🇿",uz:"Qozog'iston",ru:"Казахстан",en:"Kazakhstan",val:"kzt"},
  {code:"kg",dial:"+996",flag:"🇰🇬",uz:"Qirg'iziston",ru:"Кыргызстан",en:"Kyrgyzstan",val:"kgs"},
  {code:"tj",dial:"+992",flag:"🇹🇯",uz:"Tojikiston",ru:"Таджикистан",en:"Tajikistan",val:"tjs"},
  {code:"tr",dial:"+90",flag:"🇹🇷",uz:"Turkiya",ru:"Турция",en:"Turkey",val:"try"},
  {code:"us",dial:"+1",flag:"🇺🇸",uz:"AQSH",ru:"США",en:"USA",val:"usd"},
  {code:"ae",dial:"+971",flag:"🇦🇪",uz:"BAA (Dubay)",ru:"ОАЭ",en:"UAE",val:"aed"},
  {code:"gb",dial:"+44",flag:"🇬🇧",uz:"Buyuk Britaniya",ru:"Великобритания",en:"UK",val:"gbp"},
  {code:"eu",dial:"+",flag:"🇪🇺",uz:"Yevropa",ru:"Европа",en:"Europe",val:"eur"},
];

export const QUICK_ADD = [
  {id:"ovqat",    emoji:"🍔",kat:"oziq",    uz:"Ovqat",    ru:"Еда",        en:"Food"},
  {id:"taxi",     emoji:"🚕",kat:"transport",uz:"Transport",ru:"Транспорт",  en:"Transport"},
  {id:"kofe",     emoji:"☕",kat:"oziq",    uz:"Kofe",     ru:"Кофе",       en:"Coffee"},
  {id:"bozor",    emoji:"🛒",kat:"oziq",    uz:"Bozor",    ru:"Продукты",   en:"Groceries"},
  {id:"benzin",   emoji:"⛽",kat:"transport",uz:"Benzin",   ru:"Бензин",     en:"Fuel"},
  {id:"dorixona", emoji:"💊",kat:"sog",     uz:"Dorixona", ru:"Аптека",     en:"Pharmacy"},
];

export const VAZIFA_PRESETS = [
  {emoji:"🧹",uz:"Xonani yig'ishtirish",ru:"Убрать комнату",    en:"Clean room",          reward:20000},
  {emoji:"📚",uz:"Kitob o'qish",         ru:"Читать книгу",      en:"Read a book",         reward:15000},
  {emoji:"🛏️",uz:"To'shakni yig'ish",   ru:"Заправить кровать", en:"Make the bed",        reward:5000},
  {emoji:"🍽️",uz:"Idishlarni yuvish",   ru:"Помыть посуду",     en:"Wash dishes",         reward:10000},
  {emoji:"🦷",uz:"Tish yuvish",          ru:"Почистить зубы",    en:"Brush teeth",         reward:3000},
  {emoji:"🕌",uz:"Namoz o'qish",         ru:"Совершить намаз",   en:"Pray",                reward:10000},
  {emoji:"🎓",uz:"Dars tayyorlash",      ru:"Сделать уроки",     en:"Do homework",         reward:25000},
  {emoji:"🏃",uz:"Mashq qilish",         ru:"Зарядка",           en:"Exercise",            reward:8000},
  {emoji:"🌱",uz:"Gullarni sug'orish",   ru:"Полить цветы",      en:"Water plants",        reward:5000},
  {emoji:"🐕",uz:"Hayvonga qarash",      ru:"Покормить питомца", en:"Feed pet",            reward:7000},
  {emoji:"🗑️",uz:"Axlatni chiqarish",   ru:"Вынести мусор",     en:"Take out trash",      reward:5000},
  {emoji:"📖",uz:"Ingliz tili so'z yodlash",ru:"Учить англ. слова",en:"Learn English words",reward:20000},
];

export const GOAL_PRESETS = [
  {emoji:"🏠",uz:"Uy xarid qilish",    ru:"Покупка дома",     en:"Buy a house",    rang:"#10b981"},
  {emoji:"🚗",uz:"Mashina xarid qilish",ru:"Покупка машины",  en:"Buy a car",      rang:"#3b82f6"},
  {emoji:"✈️",uz:"Sayohat",            ru:"Путешествие",       en:"Travel",         rang:"#f59e0b"},
  {emoji:"🕋",uz:"Umra ziyorati",       ru:"Умра",             en:"Umrah",          rang:"#8b5cf6"},
  {emoji:"🕌",uz:"Haj amallari",        ru:"Хадж",             en:"Hajj",           rang:"#06b6d4"},
  {emoji:"💍",uz:"To'y marosimi",       ru:"Свадьба",          en:"Wedding",        rang:"#ec4899"},
  {emoji:"📱",uz:"Telefon / Texnika",   ru:"Телефон",          en:"Phone / Gadget", rang:"#6366f1"},
  {emoji:"🎓",uz:"Ta'lim / O'qish",    ru:"Образование",       en:"Education",      rang:"#ef4444"},
  {emoji:"🏥",uz:"Favqulodda jamg'arma",ru:"Резерв",           en:"Emergency",      rang:"#14b8a6"},
  {emoji:"💼",uz:"Biznes boshlash",     ru:"Бизнес",           en:"Business",       rang:"#f97316"},
  {emoji:"💻",uz:"Kompyuter / Noutbuk", ru:"Компьютер",       en:"Computer",     rang:"#0ea5e9"},
  {emoji:"🛠️",uz:"Uy ta'miri",         ru:"Ремонт",           en:"Home repair",  rang:"#84cc16"},
  {emoji:"💎",uz:"Tilla taqinchoq",     ru:"Украшения",       en:"Jewelry",      rang:"#eab308"},
  {emoji:"🐑",uz:"Qurbonlik",           ru:"Курбан",           en:"Qurbani",      rang:"#a855f7"},
  {emoji:"🏍️",uz:"Mototsikl",          ru:"Мотоцикл",       en:"Motorcycle",   rang:"#f43f5e"},
  {emoji:"🎉",uz:"Bayram / Marosim",    ru:"Праздник",         en:"Celebration",  rang:"#22c55e"},
];

export const KID_GOAL_PRESETS = [
  {emoji:"🚲",uz:"Velosiped",               ru:"Велосипед",             en:"Bicycle",     rang:"#10b981"},
  {emoji:"📱",uz:"Telefon",                 ru:"Телефон",               en:"Phone",       rang:"#6366f1"},
  {emoji:"🎮",uz:"O'yin pristavka",         ru:"Игровая приставка",     en:"Game console",rang:"#8b5cf6"},
  {emoji:"🧸",uz:"O'yinchoq",              ru:"Игрушка",               en:"Toy",         rang:"#ec4899"},
  {emoji:"⚽",uz:"Futbol to'pi",           ru:"Мяч",                   en:"Football",    rang:"#f59e0b"},
  {emoji:"📚",uz:"Kitoblar",               ru:"Книги",                 en:"Books",       rang:"#ef4444"},
  {emoji:"🎨",uz:"Rasm chizish to'plami", ru:"Набор для рисования",   en:"Art set",     rang:"#06b6d4"},
  {emoji:"🛴",uz:"Samokat",               ru:"Самокат",               en:"Scooter",     rang:"#14b8a6"},
  {emoji:"🎧",uz:"Naushnik",              ru:"Наушники",              en:"Headphones",  rang:"#a855f7"},
  {emoji:"👟",uz:"Krossovka",             ru:"Кроссовки",             en:"Sneakers",    rang:"#f97316"},
  {emoji:"🎂",uz:"Tug'ilgan kun",         ru:"День рождения",         en:"Birthday",    rang:"#ec4899"},
  {emoji:"💰",uz:"Jamg'arma",             ru:"Накопления",            en:"Savings",     rang:"#10b981"},
  {emoji:"⌚",uz:"Aqlli soat",            ru:"Смарт-часы",       en:"Smart watch",  rang:"#0ea5e9"},
  {emoji:"🛹",uz:"Skeytbord",            ru:"Скейтборд",        en:"Skateboard",   rang:"#84cc16"},
  {emoji:"🎸",uz:"Gitara",               ru:"Гитара",            en:"Guitar",       rang:"#f43f5e"},
  {emoji:"🐹",uz:"Uy hayvoni",           ru:"Питомец",          en:"Pet",          rang:"#eab308"},
];

export const ONB_SLIDES = [
  // color: token kaliti — komponentda th/GARDEN/PREMIUM orqali yechiladi (hex YO'Q)
  {id:"intro", color:"ac",
   titleUz:"Oila Hisobchi", titleRu:"Oila Hisobchi", titleEn:"Oila Hisobchi",
   descUz:"Oilangizning moliyaviy hamrohi. Sodda. Ishonchli. Sizniki.",
   descRu:"Финансовый помощник вашей семьи. Просто. Надёжно. Ваше.",
   descEn:"Your family's financial companion. Simple. Trusted. Yours."},
  {id:"budget", color:"gr",
   titleUz:"Oilaviy byudjet", titleRu:"Семейный бюджет", titleEn:"Family budget",
   descUz:"Daromad, xarajat va qarzlar — butun oila uchun bir joyda.",
   descRu:"Доходы, расходы и долги — всё в одном месте для всей семьи.",
   descEn:"Income, expenses and debts — all in one place for the family."},
  {id:"garden", color:"garden",
   titleUz:"Baraka Bog'i", titleRu:"Сад Барака", titleEn:"Baraka Garden",
   descUz:"Tejamkorlik daraxtingizni oila bilan birga o'stiring.",
   descRu:"Растите дерево бережливости всей семьёй.",
   descEn:"Grow your savings tree together as a family."},
  {id:"farzand", color:"ac",
   titleUz:"Farzandlar uchun Bilim Bozori", titleRu:"Рынок знаний для детей", titleEn:"Knowledge Market for kids",
   descUz:"Farzandingiz vazifa bajarib, o'ynab pul ishlaydi va moliyani boshqarishni o'rganadi.",
   descRu:"Ваш ребёнок выполняет задания, зарабатывает играя и учится управлять деньгами.",
   descEn:"Your child completes tasks, earns by playing, and learns to manage money."},
  {id:"premium", color:"gold",
   titleUz:"Premium bilan cheksiz", titleRu:"Безгранично с Premium", titleEn:"Unlimited with Premium",
   descUz:"Cheksiz maqsad, PDF/Excel eksport va foydali tavsiyalar.",
   descRu:"Безлимитные цели, экспорт PDF/Excel и полезные советы.",
   descEn:"Unlimited goals, PDF/Excel export and useful insights."},
];

export const RELATIONS = [
  {id:"ota",     emoji:"👨", uz:"Ota",          ru:"Отец",           en:"Father"},
  {id:"ona",     emoji:"👩", uz:"Ona",          ru:"Мать",           en:"Mother"},
  {id:"turmush", emoji:"💑", uz:"Turmush o'rtoq",ru:"Супруг(а)",     en:"Spouse"},
  {id:"farzand", emoji:"👦", uz:"Farzand (Katta farzand)", ru:"Ребёнок (Старший ребёнок)", en:"Child (Older child)"},
  {id:"aka",     emoji:"👨", uz:"Aka",           ru:"Старший брат",  en:"Older brother"},
  {id:"uka",     emoji:"👦", uz:"Uka",           ru:"Младший брат",  en:"Younger brother"},
  {id:"opa",     emoji:"👩", uz:"Opa",           ru:"Старшая сестра",en:"Older sister"},
  {id:"singil",  emoji:"👧", uz:"Singil",        ru:"Младшая сестра",en:"Younger sister"},
  {id:"boshqa",  emoji:"👤", uz:"Boshqa",        ru:"Другое",        en:"Other"},
];

// XAVFSIZLIK: admin endi ILOVA ICHIDA yo'q. Admin statistikasi alohida,
// mustaqil admin-sayt orqali ko'riladi (faqat Firestore Rules'dagi admin
// UID'ga ruxsat). Oddiy foydalanuvchi ilovasida admin mantiqi saqlanmaydi.
// (Eski ADMIN_TEL olib tashlandi — telefon soxtalashtirilishi mumkin edi.)

export const FAQS = {
  uz:[
    {q:"Oila kodi nima?",    a:"Oilangizga boshqa a'zolarni qo'shish uchun ishlatiladigan maxsus kod. Profil > Shaxsiy ma'lumotlar bo'limida topasiz."},
    {q:"Valyuta kurslari qayerdan?", a:"O'zbekiston Markaziy Banki rasmiy saytidan olinadi."},
    {q:"Foydali maslahat qanday ishlaydi?", a:"Tizim oylik daromad va xarajatlaringizni tahlil qilib, foydali maslahat beradi."},
    {q:"PIN kod nima uchun?", a:"Ilovaga kirish xavfsizligini ta'minlash uchun 4 raqamli PIN kod o'rnatishingiz mumkin."},
  ],
  ru:[
    {q:"Что такое код семьи?", a:"Уникальный код для добавления членов семьи."},
    {q:"Откуда берутся курсы?", a:"Данные Центрального банка Узбекистана."},
    {q:"Как работает полезный совет?", a:"Система анализирует доходы и расходы и даёт полезные рекомендации."},
    {q:"Зачем PIN код?", a:"Для безопасного входа в приложение."},
  ],
  en:[
    {q:"What is the family code?", a:"A code to add family members. Find it in Profile > Personal info."},
    {q:"Where do exchange rates come from?", a:"From the Central Bank of Uzbekistan."},
    {q:"How does useful advice work?", a:"The system analyzes your income/expenses and gives useful tips."},
    {q:"What is the PIN code for?", a:"To secure access to the app."},
  ],
};

export const TL = {
  uz:{app:"Oila Hisobchi",hi:"Salom",home:"Bosh",chart:"Grafik",goal:"Maqsad",rep:"Hisobot",
    inc:"Daromad",exp:"Xarajat",bal:"Balans",bud:"Budjet",me:"Men",hd:"Bosh",mb2:"A'zo",
    prf:"Profil",up:"Rasm yuklash",rp:"Rasmni o'chirish",ep:"Tahrirlash",un:"Ismni yangilash",
    fc2:"Oila kodi",fcd:"Oila a'zolaringizga yuboring",bll:"Budjet",mb:"Oylik budjet (so'm)",
    cl:"Kategoriya limitleri",fam:"Oila",sa:"Saqlandi",ua:"Yangilandi",lo:"Chiqish",
    sp:"sarflandi",lf:"qoldi",ex:"oshdi!",le:"limiti oshdi!",bw:"Budjetning 90% sarflandi!",
    be:"Budjet oshib ketdi!",xa:"Xarajat qo'shildi",da:"Daromad qo'shildi",ma:"Maqsad qo'shildi",
    od:"Faqat o'z yozuvingizni o'chira olasiz",fa:"Barcha maydonlarni to'ldiring",
    ea:"Summa kiriting",ec:"To'g'ri raqam kiriting",ee:"Bu email allaqachon ro'yxatda",
    ue:"Foydalanuvchi topilmadi",we:"Parol noto'g'ri",ffe:"Bunday oila kodi topilmadi",
    fc3:"Oila yaratildi!",jf2:"Oilaga qo'shildingiz!",wc:"Xush kelibsiz",sch:"Qidirish...",
    res:"Natijalar",nf2:"Topilmadi",nr:"Hali yozuv yo'q",l7:"So'nggi 7 kun",l6:"Oylik xarajatlar",
    bc:"Bu oy kategoriyalar",hm:"Kunlik faollik (30 kun)",st:"Oylik ko'rsatkichlar",
    ad:"O'rtacha kunlik",ir:"Daromad/Xarajat",bs:"Budjet tejalgan",rc:"Yozuvlar soni",
    rates:"Valyuta kurslari",rSub:"Markaziy bank kursi",ldd:"Yuklanmoqda...",all:"Hammasi",
    ed:"Xarajat taqsimoti",isr:"Daromad manbalari",bm:"A'zolar bo'yicha",
    aa:"Foydali moliyaviy maslahat",an:"Tahlil...",na:"Yangi maslahat",sv:"Saqlash",am:"Qo'shish",
    ach:"Maqsadga erishdingiz!",rem:"Qolgan",tp:"Pul qo'shish",mr:"oylik hisoboti",cn:"Bekor",
    shaxsiy:"Shaxsiy ma'lumotlar",ilovaS:"Ilova sozlamalari",xav:"Xavfsizlik",
    qol:"Qo'llab-quvvatlash",ver:"Ilova versiyasi",til:"Interfeys tili",mavzu:"Ilova mavzusi",
    kunduzi:"Kunduzgi",tungi:"Tungi",pin:"PIN kodni o'zgartirish",barmoq:"Barmoq izi bilan kirish",
    tgBot:"Rasmiy Telegram bot",faq:"Ko'p so'raladigan savollar",qoshimcha:"QO'SHIMCHA"},
  ru:{app:"Семейный Бюджет",hi:"Привет",home:"Главная",chart:"Графики",goal:"Цели",rep:"Отчёт",
    inc:"Доход",exp:"Расход",bal:"Баланс",bud:"Бюджет",me:"Я",hd:"Глава",mb2:"Участник",
    prf:"Профиль",up:"Загрузить фото",rp:"Удалить фото",ep:"Редактировать",un:"Обновить имя",
    fc2:"Код семьи",fcd:"Отправьте код членам семьи",bll:"Бюджет",mb:"Месячный бюджет (сум)",
    cl:"Лимиты категорий",fam:"Семья",sa:"Сохранено",ua:"Обновлено",lo:"Выйти",
    sp:"потрачено",lf:"осталось",ex:"превышен!",le:"лимит превышен!",
    bw:"Использовано 90% бюджета!",be:"Бюджет превышен!",xa:"Расход добавлен",da:"Доход добавлен",
    ma:"Цель добавлена",od:"Можно удалять только свои записи",fa:"Заполните все поля",
    ea:"Введите сумму",ec:"Введите корректное число",ee:"Email уже зарегистрирован",
    ue:"Пользователь не найден",we:"Неверный пароль",ffe:"Код семьи не найден",
    fc3:"Семья создана!",jf2:"Вы присоединились!",wc:"Добро пожаловать",sch:"Поиск...",
    res:"Результаты",nf2:"Не найдено",nr:"Записей пока нет",l7:"Последние 7 дней",
    l6:"Месячные расходы",bc:"Категории за месяц",hm:"Активность за 30 дней",
    st:"Показатели месяца",ad:"Средний дневной",ir:"Доход/Расход",bs:"Экономия бюджета",
    rc:"Записей за месяц",rates:"Курсы валют",rSub:"Курс ЦБ",ldd:"Загрузка...",all:"Все",
    ed:"Распределение расходов",isr:"Источники дохода",bm:"По участникам",
    aa:"Полезный финансовый совет",an:"Анализируется...",na:"Новый совет",sv:"Сохранить",am:"Добавить",
    ach:"Цель достигнута!",rem:"Осталось",tp:"Пополнение",mr:"отчёт за",cn:"Отмена",
    shaxsiy:"Личные данные",ilovaS:"Настройки",xav:"Безопасность",qol:"Поддержка",
    ver:"Версия",til:"Язык",mavzu:"Тема",kunduzi:"Светлый",tungi:"Тёмный",
    pin:"Изменить PIN",barmoq:"Отпечаток",tgBot:"Telegram бот",faq:"FAQ",qoshimcha:"ДОПОЛНИТЕЛЬНО"},
  en:{app:"Family Budget",hi:"Hello",home:"Home",chart:"Charts",goal:"Goals",rep:"Report",
    inc:"Income",exp:"Expense",bal:"Balance",bud:"Budget",me:"Me",hd:"Head",mb2:"Member",
    prf:"Profile",up:"Upload photo",rp:"Remove photo",ep:"Edit",un:"Update name",
    fc2:"Family code",fcd:"Share with family",bll:"Budget",mb:"Monthly budget (UZS)",
    cl:"Category limits",fam:"Family",sa:"Saved",ua:"Updated",lo:"Sign out",
    sp:"spent",lf:"left",ex:"exceeded!",le:"limit exceeded!",
    bw:"90% of budget used!",be:"Budget exceeded!",xa:"Expense added",da:"Income added",
    ma:"Goal added",od:"You can only delete your own records",fa:"Fill all fields",
    ea:"Enter amount",ec:"Enter valid number",ee:"Email already registered",
    ue:"User not found",we:"Wrong password",ffe:"Family code not found",
    fc3:"Family created!",jf2:"Joined family!",wc:"Welcome",sch:"Search...",
    res:"Results",nf2:"Not found",nr:"No records yet",l7:"Last 7 days",l6:"Monthly expenses",
    bc:"This month",hm:"Activity 30 days",st:"Monthly stats",ad:"Avg daily",ir:"Income/Expense",
    bs:"Budget saved",rc:"Records",rates:"Exchange rates",rSub:"Central Bank",ldd:"Loading...",
    all:"All",ed:"Expense breakdown",isr:"Income sources",bm:"By members",
    aa:"Useful Financial advice",an:"Analyzing...",na:"New advice",sv:"Save",am:"Add",
    ach:"Goal achieved!",rem:"Remaining",tp:"Add funds",mr:"monthly report",cn:"Cancel",
    shaxsiy:"Personal info",ilovaS:"App settings",xav:"Security",qol:"Support",
    ver:"Version",til:"Language",mavzu:"Theme",kunduzi:"Light",tungi:"Dark",
    pin:"Change PIN",barmoq:"Fingerprint",tgBot:"Telegram Bot",faq:"FAQ",qoshimcha:"ADDITIONAL"},
  kk:{app:"Отбасылық бюджет",hi:"Сәлем",home:"Басты бет",chart:"Графиктер",goal:"Мақсаттар",rep:"Есеп",
    inc:"Кіріс",exp:"Шығыс",bal:"Баланс",bud:"Бюджет",me:"Мен",hd:"Басшы",mb2:"Мүше",
    prf:"Профиль",up:"Суретті жүктеу",rp:"Суретті жою",ep:"Өңдеу",un:"Атты жаңарту",
    fc2:"Отбасы коды",fcd:"Кодты отбасы мүшелеріне жіберіңіз",bll:"Бюджет",mb:"Айлық бюджет (теңге/сум)",
    cl:"Санат лимиттері",fam:"Отбасы",sa:"Сақталды",ua:"Жаңартылды",lo:"Шығу",
    sp:"жұмсалды",lf:"қалды",ex:"асып кетті!",le:"лимит асып кетті!",bw:"Бюджеттің 90%-ы жұмсалды!",
    be:"Бюджет асып кетті!",xa:"Шығыс қосылды",da:"Кіріс қосылды",ma:"Мақсат қосылды",
    od:"Тек өз жазбаларыңызды өшіре аласыз",fa:"Барлық өрістерді толтырыңыз",
    ea:"Соманы енгізіңіз",ec:"Дұрыс санды енгізіңіз",ee:"Бұл email тіркеліп қойған",
    ue:"Пайдаланушы табылмады",we:"Құпия сөз қате",ffe:"Мұндай отбасы коды табылмады",
    fc3:"Отбасы құрылды!",jf2:"Отбасына қосылдыңыз!",wc:"Қош келдіңіз",sch:"Іздеу...",
    res:"Нәтижелер",nf2:"Табылмады",nr:"Әлі жазбалар жоқ",l7:"Соңғы 7 күн",l6:"Айлық шығыстар",
    bc:"Осы айдағы санаттар",hm:"Күнделікті белсенділік (30 күн)",st:"Айлық көрсеткіштер",
    ad:"Орташа күнделікті",ir:"Кіріс/Шығыс",bs:"Бюджетті үнемдеу",rc:"Жазылымдар саны",
    rates:"Валюта бағамдары",rSub:"Орталық банк бағамы",ldd:"Жүктелуде...",all:"Барлығы",
    ed:"Шығыстарды бөлу",isr:"Кіріс көздері",bm:"Мүшелер бойынша",
    aa:"Пайдалы қаржылық кеңес",an:"Талдау...",na:"Жаңа кеңес",sv:"Сақтау",am:"Қосу",
    ach:"Мақсатқа жеттіңіз!",rem:"Қалғаны",tp:"Ақша қосу",mr:"айлық есебі",cn:"Бас тарту",
    shaxsiy:"Жеке мәліметтер",ilovaS:"Қосымша параметрлері",xav:"Қауіпсіздік",
    qol:"Қолдау",ver:"Қосымша нұсқасы",til:"Интерфейс тілі",mavzu:"Қосымша тақырыбы",
    kunduzi:"Күндізгі",tungi:"Түнгі",pin:"PIN кодты өзгерту",barmoq:"Саусақ ізімен кіру",
    tgBot:"Ресми Telegram бот",faq:"Жиі қойылатын сұрақтар",qoshimcha:"ҚОСЫМША"},
  ky:{app:"Үй-бүлөлүк бюджет",hi:"Салам",home:"Башкы бет",chart:"Графиктер",goal:"Максаттар",rep:"Отчёт",
    inc:"Киреше",exp:"Чыгым",bal:"Баланс",bud:"Бюджет",me:"Мен",hd:"Башчы",mb2:"Мүчө",
    prf:"Профиль",up:"Сүрөт жүктөө",rp:"Сүрөттү өчүрүү",ep:"Түзөтүү",un:"Атын жаңыртуу",
    fc2:"Үй-бүлө коду",fcd:"Кодду үй-бүлө мүчөлөрүнө жөнөтүңүз",bll:"Бюджет",mb:"Айлык бюджет (сом)",
    cl:"Категория лимиттери",fam:"Үй-бүлө",sa:"Сакталды",ua:"Жаңартылды",lo:"Чыгуу",
    sp:"коротулду",lf:"калды",ex:"ашып кетти!",le:"лимит ашып кетти!",bw:"Бюджеттин 90% коротулду!",
    be:"Бюджет ашып кетти!",xa:"Чыгым кошулду",da:"Киреше кошулду",ma:"Максат кошулду",
    od:"Өзүңүздүн гана жазууларыңызды өчүрө аласыз",fa:"Бардык талааларды толтуруңуз",
    ea:"Сумманы киргизиңиз",ec:"Туура санды киргизиңиз",ee:"Бул email катталган",
    ue:"Колдонуучу табылган жок",we:"Купия сөз туура эмес",ffe:"Үй-бүлө коду табылган жок",
    fc3:"Үй-бүлө түзүлдү!",jf2:"Үй-бүлөгө кошулдуңуз!",wc:"Кош келиңиз",sch:"Издөө...",
    res:"Жыйынтыктар",nf2:"Табылган жок",nr:"Азырынча жазуу жок",l7:"Акыркы 7 күн",l6:"Айлык чыгымдар",
    bc:"Ушул айдагы категориялар",hm:"Күнүмдүк активдүүлүк (30 күн)",st:"Айлык көрсөткүчтөр",
    ad:"Орточо күнүмдүк",ir:"Киреше/Чыгым",bs:"Бюджетти үнөмдөө",rc:"Жазуулардын саны",
    rates:"Валюта курстары",rSub:"Борбордук банк курсу",ldd:"Жүктөлүүдө...",all:"Баары",
    ed:"Чыгымдарды бөлүштүрүү",isr:"Киреше булактары",bm:"Мүчөлөр боюнча",
    aa:"Пайдалуу финансылык кеңеш",an:"Талдоо...",na:"Жаңы кеңеш",sv:"Сактоо",am:"Кошуу",
    ach:"Максатка жеттіңіз!",rem:"Калганы",tp:"Акча кошуу",mr:"айлык отчёту",cn:"Жокко чыгаруу",
    shaxsiy:"Жеке маалыматтар",ilovaS:"Тиркеме жөндөөлөрү",xav:"Коопсуздук",
    qol:"Колдоо",ver:"Тиркеме версиясы",til:"Забони интерфейс",mavzu:"Тиркеме темасы",
    kunduzi:"Күндүзгү",tungi:"Түнкү",pin:"PIN кодду өзгөртүү",barmoq:"Манжа изи менен кирүү",
    tgBot:"Расмий Telegram бот",faq:"Көп берилүүчү суроолор",qoshimcha:"КОШУМЧА"},
  tg:{app:"Бюдҷети оилавӣ",hi:"Салом",home:"Саҳифаи асосӣ",chart:"Графикҳо",goal:"Ҳадафҳо",rep:"Ҳисобот",
    inc:"Даромад",exp:"Хароҷот",bal:"Балланс",bud:"Бюдҷет",me:"Ман",hd:"Роҳбар",mb2:"Узв",
    prf:"Профил",up:"Боркунии акс",rp:"Ҳазфи акс",ep:"Таҳрир",un:"Навсозии ном",
    fc2:"Коди оила",fcd:"Кодро ба узви оила фиристед",bll:"Бюдҷет",mb:"Бюдҷети моҳона (сомонӣ)",
    cl:"Лимитҳои категория",fam:"Оила",sa:"Захира шуд",ua:"Навсозӣ шуд",lo:"Хуроҷ",
    sp:"сарф шуд",lf:"монд",ex:"гузашт!",le:"лимит гузашт!",bw:"90%-и бюджет сарф шуд!",
    be:"Бюдҷет гузашт!",xa:"Хароҷот илова шуд",da:"Даромад илова шуд",ma:"Ҳадаф илова шуд",
    od:"Шумо танҳо сабтҳои худро ҳазф карда метавонед",fa:"Ҳамаи майдонҳоро пур кунед",
    ea:"Суммаро ворид кунед",ec:"Рақами дурустро ворид кунед",ee:"Ин email аллакай сабт шудааст",
    ue:"Корбар ёфт нашуд",we:"Рамз нодуруст аст",ffe:"Коди оила ёфт нашуд",
    fc3:"Оила сохта шуд!",jf2:"Шумо ба оила ҳамроҳ шудед!",wc:"Хуш омадед",sch:"Ҷустуҷӯ...",
    res:"Натиҷаҳо",nf2:"Ёфт нашуд",nr:"Ҳанӯз сабт нест",l7:"7 рӯзи охир",l6:"Хароҷоти моҳона",
    bc:"Категорияҳои ин моҳ",hm:"Фаъолияти рӯзона (30 рӯз)",st:"Нишондиҳандаҳои моҳона",
    ad:"Миёнаи рӯзона",ir:"Даромад/Хароҷот",bs:"Сарфаи бюджет",rc:"Шумораи сабтҳо",
    rates:"Қурби асъор",rSub:"Қурби бонки марказӣ",ldd:"Дар ҳоли боркунӣ...",all:"Ҳама",
    ed:"Тақсимоти хароҷот",isr:"Манбаъҳои даромад",bm:"Аз рӯи узвҳо",
    aa:"Машварати молиявии муфид",an:"Таҳлил...",na:"Машварати нав",sv:"Захира кардан",am:"Илова кардан",
    ach:"Ба ҳадаф расидед!",rem:"Мондааст",tp:"Иловаи маблағ",mr:"ҳисоботи моҳона",cn:"Бекор кардан",
    shaxsiy:"Маълумоти шахсӣ",ilovaS:"Танзимоти барнома",xav:"Амният",
    qol:"Дастгирӣ",ver:"Версияи барнома",til:"Забони интерфейс",mavzu:"Мавзӯи барнома",
    kunduzi:"Рӯзона",tungi:"Шабона",pin:"Иваз кардани PIN коди",barmoq:"Вуруд бо изи ангушт",
    tgBot:"Боти расмии Telegram",faq:"Саволҳои зуд-зуд додашаванда",qoshimcha:"ИЛОВАГӢ"},
  qr:{app:"Oila Hisobchisi",hi:"Salom",home:"Bas bet",chart:"Grafik",goal:"Maqset",rep:"Esabat",
    inc:"Kirim",exp:"Shig'is",bal:"Balans",bud:"Budjet",me:"Men",hd:"Basliq",mb2:"Ag'za",
    prf:"Profil",up:"Su'vret ju'klesh",rp:"Su'vretti o'shiriw",ep:"Redaktorlaw",un:"Atg'a o'zgeris",
    fc2:"Oila kodi",fcd:"Oila ag'zalarin'izg'a jiberin'",bll:"Budjet",mb:"Ayliq budjet (swm)",
    cl:"Kategoriya limitleri",fam:"Oila",sa:"Saqlandi",ua:"Jan'arildi",lo:"Shig'iw",
    sp:"shig'in boldi",lf:"qaldi",ex:"asti!",le:"limiti asti!",bw:"Budjettin' 90% sarplandi!",
    be:"Budjet asip ketti!",xa:"Shig'is qosildi",da:"Kirim qosildi",ma:"Maqset qosildi",
    od:"Tek o'zin'izdin' jazg'anin'izdi o'shire alasiz",fa:"Barlik maydanlardi toldirin'",
    ea:"Summa kiritin'",ec:"Tug'ri san kiritin'",ee:"Bul email dizimde bar",
    ue:"Paydalaniwshi tabilmadi",we:"Parol qa'te",ffe:"Bunday oila kodi tabilmadi",
    fc3:"Oila jaratildi!",jf2:"Oilag'a qosildin'iz!",wc:"Xush keldin'iz",sch:"Izlew...",
    res:"Na'tiyjeler",nf2:"Tabilmadi",nr:"Hali jazba joq",l7:"Song'i 7 ku'n",l6:"Ayliq shig'islar",
    bc:"Bul aydag'i kategoriyalar",hm:"Ku'nlik belsendilik (30 ku'n)",st:"Ayliq ko'rsetkishler",
    ad:"Ortasha ku'nlik",ir:"Kirim/Shig'is",bs:"Budjet u'nemlendi",rc:"Jazbalar sani",
    rates:"Valyuta kurslari",rSub:"Orayliq bank kursi",ldd:"Ju'klenbekte...",all:"Barlig'i",
    ed:"Shig'is taqsimati",isr:"Kirim derekleri",bm:"Ag'zalar boyinsha",
    aa:"Paydali qarjiliq ma'sla'hat",an:"Talqilaw...",na:"Jan'a ma'sla'hat",sv:"Saqlaw",am:"Qosiw",
    ach:"Maqsetke eristin'iz!",rem:"Qalg'an",tp:"Pul qosiw",mr:"ayliq esabati",cn:"Biykar etiw",
    shaxsiy:"Shaxsey mag'lu'matlar",ilovaS:"Ilova sozlamalari",xav:"Qa'wipsizlik",
    qol:"Qollap-quvvatlaw",ver:"Ilova versiyasi",til:"Interfeys tili",mavzu:"Ilova mavzusi",
    kunduzi:"Ku'ndizgi",tungi:"Tu'ngi",pin:"PIN kodti o'zgeris",barmoq:"Barmoq izi menen kiriw",
    tgBot:"Rasmiy Telegram bot",faq:"Ko'p soralatug'in sorawlar",qoshimcha:"QOS'IMCHA"},
};
